<!DOCTYPE html>
<html lang="en">


<!-- Mirrored from live.themewild.com/eduka/alumni.html by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 26 Jul 2025 10:31:52 GMT -->
<head>
    <!-- meta tags -->
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="keywords" content="">

    <!-- title -->
    <title>Eduka - School, College, University And Courses HTML5 Template</title>

    <!-- favicon -->
    <link rel="icon" type="image/x-icon" href="assets/img/logo/favicon.png">

        <?php
    include 'common/header-link.php';
    ?>

<style>
       #gallery-year .gallery-img {
            
            object-fit: cover;
            border-radius: 10px;
        }

       #gallery-year .gallery-item {
            display: none;
        }

       #gallery-year .gallery-item.active {
            display: block;
        }

       #gallery-year .nav-pills .nav-link.active {
            background-color: #fda31b;
            color:white;
        }
        #gallery-year .nav-pills .nav-link {
            color:black;
        }
         #gallery-year .nav-pills .nav-link:hover {
            color:white;
        }

       #gallery-year .gallery-item {
            display: none;
        }

       #gallery-year .gallery-item.active {
            display: block;
        }

       
    </style>
</head>

<body>

    <!-- preloader -->
    <div class="preloader">
        <div class="loader-book">
            <div class="loader-book-page"></div>
            <div class="loader-book-page"></div>
            <div class="loader-book-page"></div>
        </div>
    </div>
    <!-- preloader end -->


    <!-- header area -->
       <?php
    include 'common/header.php';
    ?>
    <!-- header area end -->


    <!-- popup search -->
    <div class="search-popup">
        <button class="close-search"><span class="far fa-times"></span></button>
        <form action="#">
            <div class="form-group">
                <input type="search" name="search-field" placeholder="Search Here..." required>
                <button type="submit"><i class="far fa-search"></i></button>
            </div>
        </form>
    </div>
    <!-- popup search end -->



    <main class="main">

        <!-- breadcrumb -->
        <div class="site-breadcrumb" style="background: url(assets/img/breadcrumb/01.jpg)">
            <div class="container">
                <h2 class="breadcrumb-title">Placement Gallery</h2>
                <ul class="breadcrumb-menu">
                    <li><a href="index.php">Home</a></li>
                    <li class="active">Placement Gallery</li>
                </ul>
            </div>
        </div>
        <!-- breadcrumb end -->


        


       

        <!-- testimonial area -->
        <div class="testimonial-area bg py-120">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 mx-auto">
                        <div class="site-heading text-center">
                            <span class="site-title-tagline"><i class="far fa-book-open-reader"></i> Gallery</span>
                            <h2 class="site-title">Placement <span>Gallery</span></h2>
                            <p>Placement Gallery showcases student success through top campus recruitments and memorable placement moments.
                                A glimpse into our proud achievements and career milestones.</p>
                        </div>
                    </div>
                </div>
            
    

    <div id="gallery-year" >
       

            <!-- Year Tabs -->
            <ul class="nav nav-pills justify-content-center mb-4" id="yearTabs">
                <!-- Tabs will be generated by JS -->
            </ul>
        

                <div class="row" id="gallery">

            
                 <div class="col-lg-4">
                <div class="col-md-6 col-lg-4 mb-4 gallery-item" data-year="2023">
                    <img src="assets\img\placement_gallery\23_1.jpeg" class="gallery-img">
                </div>
                </div>

               <div class="col-lg-4">
                <div class="col-md-6 col-lg-4 mb-4 gallery-item" data-year="2023">
                    <img src="assets\img\placement_gallery\23_2.jpg" class="gallery-img">
                </div>
                </div>

               <div class="col-lg-4">
                <div class="col-md-6 col-lg-4 mb-4 gallery-item" data-year="2023">
                    <img src="assets\img\placement_gallery\23_3.jpg" class="gallery-img">
                </div>
                </div>

                <div class="col-lg-4">
                <div class="col-md-6 col-lg-4 mb-4 gallery-item" data-year="2023">
                    <img src="assets\img\placement_gallery\23_4.jpg" class="gallery-img">
                </div>
                </div>

                <div class="col-lg-4">
                <div class="col-md-6 col-lg-4 mb-4 gallery-item" data-year="2023">
                    <img src="assets\img\placement_gallery\23_5.jpg" class="gallery-img">
                </div>
                </div>

               <div class="col-lg-4">
                <div class="col-md-6 col-lg-4 mb-4 gallery-item" data-year="2023">
                    <img src="assets\img\placement_gallery\23_6.jpg" class="gallery-img">
                </div>
                </div>

        


                <!-- 2023-24 -->
                <div class="col-lg-4">
                <div class="col-md-6 col-lg-4 mb-4 gallery-item" data-year="2024">
                    <img src="assets\img\placement_gallery\24_1.jpeg" class="gallery-img">
                </div>
                </div>

                <div class="col-lg-4">
                <div class="col-md-6 col-lg-4 mb-4 gallery-item" data-year="2024">
                    <img src="assets\img\placement_gallery\24_2.jpeg" class="gallery-img">
                </div>
                </div>

                <div class="col-lg-4">
                <div class="col-md-6 col-lg-4 mb-4 gallery-item" data-year="2024">
                    <img src="assets\img\placement_gallery\24_3.jpeg" class="gallery-img">
                </div>
                </div>


             <!-- 2024-25 -->
                <div class="col-lg-4">
                <div class="col-md-6 col-lg-4 mb-4 gallery-item" data-year="2025">
                    <img src="assets\img\placement_gallery\25_14.jpeg" class="gallery-img">
                </div>
                </div>


               
                <div class="col-lg-4">
                <div class="col-md-6 col-lg-4 mb-4 gallery-item" data-year="2025">
                    <img src="assets\img\placement_gallery\25_1.jpeg" class="gallery-img">
                </div>
                </div>

                <div class="col-lg-4">
                <div class="col-md-6 col-lg-4 mb-4 gallery-item" data-year="2025">
                    <img src="assets\img\placement_gallery\25_2.jpeg" class="gallery-img">
                </div>
                </div>

               <div class="col-lg-4">
                <div class="col-md-6 col-lg-4 mb-4 gallery-item" data-year="2025">
                    <img src="assets\img\placement_gallery\25_3.jpeg" class="gallery-img">
                </div>
                </div>

               <div class="col-lg-4">
                <div class="col-md-6 col-lg-4 mb-4 gallery-item" data-year="2025">
                    <img src="assets\img\placement_gallery\25_4.jpeg" class="gallery-img">
                </div>
                </div>

                <div class="col-lg-4">
                <div class="col-md-6 col-lg-4 mb-4 gallery-item" data-year="2025">
                    <img src="assets\img\placement_gallery\25_5.jpeg" class="gallery-img">
                </div>
                </div>

                <div class="col-lg-4">
                <div class="col-md-6 col-lg-4 mb-4 gallery-item" data-year="2025">
                    <img src="assets\img\placement_gallery\25_6.jpeg" class="gallery-img">
                </div>
                </div>

               <div class="col-lg-4">
                <div class="col-md-6 col-lg-4 mb-4 gallery-item" data-year="2025">
                    <img src="assets\img\placement_gallery\25_7.jpeg" class="gallery-img">
                </div>
                </div>

                <div class="col-lg-4">
                <div class="col-md-6 col-lg-4 mb-4 gallery-item" data-year="2025">
                    <img src="assets\img\placement_gallery\25_8.jpeg" class="gallery-img">
                </div>
                </div>

             <div class="col-lg-4">
                <div class="col-md-6 col-lg-4 mb-4 gallery-item" data-year="2025">
                    <img src="assets\img\placement_gallery\25_9.jpeg" class="gallery-img">
                </div>
                </div>

                 <div class="col-lg-4">
                <div class="col-md-6 col-lg-4 mb-4 gallery-item" data-year="2025">
                    <img src="assets\img\placement_gallery\25_10.jpeg" class="gallery-img">
                </div>
                </div>

                 <div class="col-lg-4">
                <div class="col-md-6 col-lg-4 mb-4 gallery-item" data-year="2025">
                    <img src="assets\img\placement_gallery\25_11.jpeg" class="gallery-img">
                </div>
                </div>

                 <div class="col-lg-4">
                <div class="col-md-6 col-lg-4 mb-4 gallery-item" data-year="2025">
                    <img src="assets\img\placement_gallery\25_12.jpeg" class="gallery-img">
                </div>
                </div>

                <div class="col-lg-4">
                <div class="col-md-6 col-lg-4 mb-4 gallery-item" data-year="2025">
                    <img src="assets\img\placement_gallery\25_13.jpeg" class="gallery-img">
                </div>
                </div>

                 <div class="col-lg-4">
                <div class="col-md-6 col-lg-4 mb-4 gallery-item" data-year="2025">
                    <img src="assets\img\placement_gallery\25_14.jpeg" class="gallery-img">
                </div>
                </div>

            </div>
        </div>



    </div>

    <!-- JAVA SCRIPT -->
    <script>
        // Generate year tabs from 2023 to 2025
        const tabcontainer = document.getElementById('yearTabs');
        for (let year = 2023; year <= 2025; year++) {
            const li = document.createElement('li');
            li.classList.add('nav-item');
            li.innerHTML = `
      <button class="nav-link ${year === 2025 ? 'active' : ''}" data-bs-toggle="pill" data-year="${year}">
        ${year}
      </button>
     `;
            tabContainer.appendChild(li);
        }

        // Filtering logic
        function filterGallery(year) {
            const items = document.querySelectorAll('.gallery-item');
            items.forEach(item => {
                const itemYear = item.getAttribute('data-year');
                if (itemYear === year.toString()) {
                    item.classList.add('active');
                } else {
                    item.classList.remove('active');
                }
            });
        }

        // Initial load - show 2024
        filterGallery(2025);

        // Add event listeners to tabs
        tabContainer.addEventListener('click', function (e) {
            if (e.target.matches('button[data-year]')) {
                const year = e.target.getAttribute('data-year');
                document.querySelectorAll('#yearTabs .nav-link').forEach(btn => btn.classList.remove('active'));
                e.target.classList.add('active');
                filterGallery(year);
            }
        });
    </script>

    <script>
        const tabContainer = document.getElementById('yearTabs');

        // Add "All" tab first
        const allTab = document.createElement('li');
        allTab.classList.add('nav-item');
        allTab.innerHTML = `
    <button class="nav-link active" data-bs-toggle="pill" data-year="all">
      All
    </button>
  `;
        tabContainer.appendChild(allTab);

        // Add year tabs from 2023 to 2025
        for (let year = 2023; year <= 2025; year++) {
            const li = document.createElement('li');
            li.classList.add('nav-item');
            li.innerHTML = `
      <button class="nav-link" data-bs-toggle="pill" data-year="${year}">
        ${year}
      </button>
    `;
            tabContainer.appendChild(li);
        }

        // Filtering logic
        function filterGallery(year) {
            const items = document.querySelectorAll('.gallery-item');
            items.forEach(item => {
                const itemYear = item.getAttribute('data-year');
                if (year === 'all' || itemYear === year.toString()) {
                    item.classList.add('active');
                } else {
                    item.classList.remove('active');
                }
            });
        }

        // Initial load - show all
        filterGallery('all');

        // Add event listeners to tabs
        tabContainer.addEventListener('click', function (e) {
            if (e.target.matches('button[data-year]')) {
                const year = e.target.getAttribute('data-year');
                document.querySelectorAll('#yearTabs .nav-link').forEach(btn => btn.classList.remove('active'));
                e.target.classList.add('active');
                filterGallery(year);
            }
        });
    </script>


            </div>
        </div>
        <!-- testimonial area end -->
        

    </main>



    <!-- footer area -->
        <?php
    include 'common/footer.php';
    ?>
    <!-- footer area end -->




    <!-- scroll-top -->
    <a href="#" id="scroll-top"><i class="far fa-arrow-up-from-arc"></i></a>
    <!-- scroll-top end -->


     <?php
    include 'common/footer-link.php';
    ?>
</body>


<!-- Mirrored from live.themewild.com/eduka/alumni.html by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 26 Jul 2025 10:31:55 GMT -->
</html>